function out = ApplyLaplace(in)

if isvector(in)
    out = reshape( ...
        conv( ...
        MirrorBounds(opts.in(:), 1, 1), ...
        [1 ; -2 ; 1], 'valid'), ...
        size(opts.in) );
else
    
end
end
