function out = OptimizeMaskValue(u,c,f)
%% Optimize interpolation influence on data sites.
[row col] = size(f);
D = LaplaceM(row, col, ...
    'KnotsR',[-1 0 1],'KnotsC',[-1 0 1], ...
    'Boundary', 'Neumann');
M = spdiags( u-f+D*u , 0 , numel(f) , numel(f) );
[out, flag, relres, iter] = lsqr( ...
    (M\D), D*u, ...
    1e-5, 512, ...
    speye(size(M)), speye(size(M)), c );

if flag ~= 0
    warning('GVO:stop', 'GVO stopped with flag %g, rel. res. %g at it. %g', ...
        flag, relres, iter );
end
end
