function out = ReturnDocString(funName)

if nargin == 0
    name = '[ out ] = newFunction( in )';
else
    name = funName;
end

author = 'Laurent Hoeltgen';
email = '<laurent.hoeltgen@gmail.com>';
year = datestr(now,'yyyy');
revision = ['Last revision on: ' datestr(now, 'dd.mm.yyyy HH:MM')];

out = sprintf( [ ...
    '%%%% Short description.\n' ...
    '%%\n' ...
    '%% %s\n' ...
    '%%\n' ...
    '%% Input parameters (required):\n' ...
    '%%\n' ...
    '%%\n' ...
    '%%\n' ...
    '%% Input parameters (optional):\n' ...
    '%%\n' ...
    '%%\n' ...
    '%%\n' ...
    '%% Output parameters:\n' ...
    '%%\n' ...
    '%%\n' ...
    '%%\n' ...
    '%% Description:\n' ...
    '%%\n' ...
    '%%\n' ...
    '%%\n' ...
    '%% Example:\n' ...
    '%%\n' ...
    '%%\n' ...
    '%%\n' ...
    '%% See also\n' ...
    '\n' ...
    '%% Copyright %s %s %s\n' ...
    '%%\n' ...
    '%% This program is free software; you can redistribute it and/or modify it under\n' ...
    '%% the terms of the GNU General Public License as published by the Free Software\n' ...
    '%% Foundation; either version 3 of the License, or (at your option) any later\n' ...
    '%% version.\n' ...
    '%%\n' ...
    '%% This program is distributed in the hope that it will be useful, but WITHOUT\n' ...
    '%% ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS\n' ...
    '%% FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more\n' ...
    '%% details.\n' ...
    '%%\n' ...
    '%% You should have received a copy of the GNU General Public License along with\n' ...
    '%% this program; if not, write to the Free Software Foundation, Inc., 51 Franklin\n' ...
    '%% Street, Fifth Floor, Boston, MA 02110-1301, USA.\n' ...
    '\n' ...
    '%% %s\n' ...
    '\n' ...
    '%%%% Check Input and Output Arguments\n' ...
    '\n' ...
    '%%%% Algorithm\n\n'], name, year, author, email, revision);

end