function UpdateFunction()
doc = matlab.desktop.editor.getActive;

% Update Copyright string.
ts = regexp( doc.Text, ...
    'Copyright (\d\d\d\d,)*(\d\d\d\d){1}','tokens');

if ~strcmp( ts{1}{end}, datestr(now,'yyyy') )
    doc.Text = regexprep( ...
        doc.Text, ...
        'Copyright (\d\d\d\d,)*(\d\d\d\d){1}', ...
        ['Copyright $1$2,' datestr(now, 'yyyy')]);
end

% Update the Last revision string.
doc.Text = regexprep( ...
    doc.Text, ...
    'Last revision on: \d\d.\d\d.\d\d\d\d \d\d:\d\d', ...
    'Last revision on: ${datestr(now, ''dd.mm.yyyy HH:MM'')}' );

end