function CheckNumOutput(obj, numArgs)
MExc = ExceptionMessage( ...
    'NumArg', ...
    'The number of input parameters does not match the number of parsed args.');
assert( ...
    (0 <= numArgs) && (numArgs <= obj.numOut), ...
    MExc.id, MExc.message );
end
