classdef Image
    %Image Represents an image in form of an n-D array.

    properties
        data
    end
        
    methods
        function obj = Image(rows,columns,varargin)
            
            error(nargchk(2, 3, nargin));
            error(nargoutchk(0, 1, nargout));

            parser = inputParser;
            
            parser.addRequired('rows', ...
                @(x) validateattributes( x, ...
                {'numeric'}, ...
                {'integer','nonnegative','scalar'}, ...
                'Image', 'rows'));
            parser.addRequired('columns', ...
                @(x) validateattributes( x, ...
                {'numeric'}, ...
                {'integer','nonnegative','scalar'}, ...
                'Image', 'columns'));
            parser.addOptional('type','double', ...
                @(x) validateattributes( x, ...
                {'char'}, ...
                {'vector'}, ...
                'Image', 'type'));
            parser.parse(rows,columns,varargin{:});
            parameters = parser.Results;
            
            try
                validatestring(parameters.type, ...
                    {'double', 'single', 'int8', 'uint8', ...
                    'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64'});
            catch
                ExcM = ExceptionMessage('BadClass', ...
                    horzcat( ...
                    'Cannot create image with pixels of type ', ...
                    parameters.type, ...
                    '. Will use double as fallback.'));
                warning(ExcM.id,ExcM.message);
                obj.data = zeros( ...
                    parameters.rows, parameters.columns, 'double');
                
                return
            end
            
            obj.data = zeros( ...
                parameters.rows, parameters.columns, parameters.type);
        end
        
    end
    
end

